### ISSUE TITLE
[Good first issue] Fix MultiPartWriterTest flaky test

### ISSUE THREAD

**Issue by superhx** [AutoMQ/automq#1072]
```
com.automq.stream.s3.operator.MultiPartWriterTest.testCopyWrite() failed, log available in /home/runner/work/automq/automq/s3stream/build/reports/testOutput/com.automq.stream.s3.operator.MultiPartWriterTest.testCopyWrite().test.stdout

Gradle Test Run :s3stream:test > Gradle Test Executor 4 > MultiPartWriterTest > testCopyWrite() FAILED
    org.opentest4j.AssertionFailedError: expected: <10> but was: <280>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:635)
        at app//com.automq.stream.s3.operator.MultiPartWriterTest.testCopyWrite(MultiPartWriterTest.java:189)
```

**Comment by superhx** [comment]
Sometimes the result is 280, other times it is 120 or 10.

**Comment by Dimitrije-Ciric** [comment]
Before adding print statements, the test rarely failed. Also when a test fails, print statements are intertwined. So, I assume some components with unhandled concurrent async behavior lead to race conditions. Or Mockito runs **"thenAnswer"** async which leads to conflict.

![Screenshot 2024-04-03 at 19 06 55](https://github.com/AutoMQ/automq/assets/90758244/295a43ee-a6d4-436e-b11b-4bf8d657bd43)
![Screenshot 2024-04-03 at 19 07 07](https://github.com/AutoMQ/automq/assets/90758244/a86d0a45-b044-4d4f-ace8-ec99465927de)

I assume this is a desired behavior:
![Screenshot 2024-04-03 at 19 16 21](https://github.com/AutoMQ/automq/assets/90758244/b1d27b76-74c4-4128-8379-bb7ad3622beb)
