### ISSUE TITLE
[Enhancement] BlockCache enhancement

### ISSUE THREAD

**Issue by superhx** [AutoMQ/automq#1087]
TODO: design doc

**Comment by superhx** [comment]
![image](https://github.com/AutoMQ/automq/assets/5719209/dbdefcc2-60ef-4c5a-8d72-0bd4c9662609)

**Comment by superhx** [comment]
[error.log](https://github.com/AutoMQ/automq/files/14967471/error.log)

```
[2024-04-13 05:51:54,186] ERROR [stream-reader-0]Error running task (com.automq.stream.utils.threads.EventLoop)
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83)
	at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:148)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
	at io.netty.buffer.AbstractDerivedByteBuf.release0(AbstractDerivedByteBuf.java:98)
	at io.netty.buffer.AbstractDerivedByteBuf.release(AbstractDerivedByteBuf.java:94)
	at com.automq.stream.s3.ObjectReader$DataBlockGroup.release(ObjectReader.java:465)
	at com.automq.stream.s3.cache.blockcache.DataBlock.free(DataBlock.java:62)
	at com.automq.stream.s3.cache.blockcache.DataBlockCache$Cache.evict0(DataBlockCache.java:193)
	at com.automq.stream.utils.threads.EventLoop.run(EventLoop.java:48)
```

```
[2024-04-13 06:49:49,908] INFO [QuorumController id=0] [CommitStreamSetObject]: successfully commit stream set object. streamSetObjectId=37816, nodeId=7, nodeEpoch=1712979070826, compacted objects: [36992, 37761, 35841, 37633, 37762, 35843, 35459, 37763, 37635, 35845, 36998, 36999, 34952, 36363, 37387, 37004, 36878,

[2024-04-13 06:59:53,190] ERROR GetObject for object e0090000/_kafka_ChaosInjectionClusterw/36878 [371469653, 372495902) fail (com.automq.stream.s3.operator.DefaultS3Operator)
java.util.concurrent.CompletionException: software.amazon.awssdk.services.s3.model.NoSuchKeyException: The specified key does not exist. (Service: S3, Status Code: 404, Request ID: DN7AKVZRJDD2KHXQ, Extended Request ID: QsHmJ/VZK66O95/+w+fnPqgeaXhDEroIkTJp+MngNLvQZG2dP72guFHcIC3zTxZOqa/FS5S1PdI=)
	at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:65)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:79)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:103)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:184)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:170)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
```

```
[2024-04-13 07:17:26,442] ERROR [BUG] nextStartOffset:1380608 is not in the range of index:1380348-1380608 (com.automq.stream.s3.cache.blockcache.StreamReader)
[2024-04-13 07:17:59,305] ERROR [BUG] nextStartOffset:1808128 is not in the range of index:1808256-1808881 (com.automq.stream.s3.cache.blockcache.StreamReader)
[2024-04-13 07:18:27,392] ERROR [BUG] nextStartOffset:1439104 is not in the range of index:1438912-1439104 (com.automq.stream.s3.cache.blockcache.StreamReader)
[2024-04-13 07:19:32,258] ERROR [BUG] nextStartOffset:1468416 is not in the range of index:1468544-1469294 (com.automq.stream.s3.cache.blockcache.StreamReader)
```

**Comment by superhx** [comment]
When memory is tight, the caches read down by Readahead are almost all evicted before being read, wasting the bandwidth of S3.
![image](https://github.com/AutoMQ/automq/assets/5719209/6a99f8ac-ea29-48d7-81b9-29560697e574)
