### ISSUE TITLE
[BUG] Clean object fail

### ISSUE THREAD

**Issue by superhx** [AutoMQ/automq#1140]
```
org.apache.kafka.common.errors.UnknownServerException: java.lang.NullPointerException: Cannot invoke "org.apache.kafka.metadata.stream.S3Object.getMarkDestroyedTimeInMs()" because "object" is null
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.kafka.metadata.stream.S3Object.getMarkDestroyedTimeInMs()" because "object" is null
        at org.apache.kafka.controller.stream.S3ObjectControlManager.checkS3ObjectsLifecycle(S3ObjectControlManager.java:305)
        at org.apache.kafka.controller.QuorumController$ControllerWriteEvent.run(QuorumController.java:868)
        at org.apache.kafka.queue.KafkaEventQueue$EventContext.run(KafkaEventQueue.java:128)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.handleEvents(KafkaEventQueue.java:211)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.run(KafkaEventQueue.java:182)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by superhx** [comment]
Controller leader ABA switch and S3ObjectControlManager.markDestroyedObjects isn't using the Timeline data structure, there is dirty data when leader change.
