### ISSUE TITLE
[Good first issue] Fix the flaky test StreamReaderTest

### ISSUE THREAD

**Issue by superhx** [AutoMQ/automq#1547]
```
Gradle Test Run :s3stream:test > Gradle Test Executor 6 > StreamReaderTest > testRead_withReadahead() FAILED
    org.opentest4j.AssertionFailedError: expected: <20> but was: <14>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:166)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:161)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:628)
        at app//com.automq.stream.s3.cache.blockcache.StreamReaderTest.testRead_withReadahead(StreamReaderTest.java:180)
```

**Comment by JunHyungJang** [comment]
Hi ! Can i get this issue ?

**Comment by superhx** [comment]
> Hi ! Can i get this issue ?

Sorry, this issue is closed by https://github.com/AutoMQ/automq/pull/1553
