### ISSUE TITLE
[Good first issue] Fix S3ObjectsImageTest#testConcurrentRefRetainAndReleaseNotThrowException flaky test

### ISSUE THREAD

**Issue by superhx** [AutoMQ/automq#1668]
```
Gradle Test Run :metadata:S3UnitTest > Gradle Test Executor 10 > S3ObjectsImageTest > testConcurrentRefRetainAndReleaseNotThrowException() FAILED
    org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
        at app//org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
        at app//org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
        at app//org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:183)
        at app//org.apache.kafka.image.S3ObjectsImageTest.testConcurrentRefRetainAndReleaseNotThrowException(S3ObjectsImageTest.java:218)
```

**Comment by chengxs258** [comment]
Let me try!

**Comment by MokshVerma** [comment]
Not sure how to replicate this or if it has been fixed. 
<img width="1198" alt="image" src="https://github.com/user-attachments/assets/ecdd6794-14b5-44b8-85fa-2d9fe41c20b7">

**Comment by yakupkariksiz** [comment]
Hello, I would like to pick up this.

**Comment by daniel-y** [comment]
Assigned, have fun @yakupkariksiz

**Comment by yakupkariksiz** [comment]
I looked into this issue and tried to reproduce the failure locally by running `S3ObjectsImageTest.testConcurrentRefRetainAndReleaseNotThrowException` multiple times. However, the test runs successfully without any failures.

Additionally, I noticed that this is a duplicate of [#1821](https://github.com/AutoMQ/automq/issues/1821), which has already been fixed. I believe we can close this ticket.

**Comment by superhx** [comment]
> #1821

Sorry for the duplicated issues
