### ISSUE TITLE
[BUG] metaStream replay forever hang.

### ISSUE THREAD

**Issue by lifepuzzlefun** [AutoMQ/automq#1729]
### Version & Environment

commit ed986c9c9298b1cb

### What went wrong?

trigger failover very often.

after one day or some time. the partition failover can't success.

### How to reproduce the issue?

trigger failover very often.
A to B, B to C, C to A

**Comment by lifepuzzlefun** [comment]
<script src="https://gist.github.com/lifepuzzlefun/e0488c1cabd575e748b2faa091765766.js"></script>

**Comment by lifepuzzlefun** [comment]
"partition_open_op_6906" #910087 daemon prio=5 os_prio=0 cpu=2.84ms elapsed=36153.21s tid=0x00007fa35c9070a0 nid=0x1855b waiting on condition  [0x00007f9a66bf4000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.7/Native Method)
	- parking to wait for  <0x00000806f2df6190> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.7/LockSupport.java:211)
	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.7/CompletableFuture.java:1864)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.7/ForkJoinPool.java:3463)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.7/ForkJoinPool.java:3434)
	at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.7/CompletableFuture.java:1898)
	at java.util.concurrent.CompletableFuture.get(java.base@17.0.7/CompletableFuture.java:2072)
	at kafka.log.streamaspect.MetaStream.replay(MetaStream.java:207)
	at kafka.log.streamaspect.ElasticLog$.apply(ElasticLog.scala:666)
	at kafka.log.streamaspect.ElasticUnifiedLog$.$anonfun$apply$2(ElasticUnifiedLog.scala:276)
	at kafka.log.streamaspect.ElasticUnifiedLog$$$Lambda$2700/0x000000080191f2e0.apply(Unknown Source)
	at kafka.log.LocalLog$.maybeHandleIOException(LocalLog.scala:739)
	at kafka.log.streamaspect.ElasticUnifiedLog$.apply(ElasticUnifiedLog.scala:270)
	at kafka.log.streamaspect.ElasticLogManager.getOrCreateLog(ElasticLogManager.scala:73)
	at kafka.log.streamaspect.ElasticLogManager$.getOrCreateLog(ElasticLogManager.scala:202)
	at kafka.log.LogManager.$anonfun$getOrCreateLog$1(LogManager.scala:1113)
	at kafka.log.LogManager$$Lambda$2517/0x00000008018e7d00.apply(Unknown Source)
	at scala.Option.getOrElse(Option.scala:201)
	at kafka.log.LogManager.getOrCreateLog(LogManager.scala:1067)
	at kafka.cluster.Partition.createLog(Partition.scala:504)
	at kafka.cluster.Partition.maybeCreate$1(Partition.scala:478)
	at kafka.cluster.Partition.createLogIfNotExists(Partition.scala:485)
	at kafka.cluster.Partition.createLogInAssignedDirectoryId(Partition.scala:991)
	at kafka.cluster.Partition.$anonfun$makeLeader$1(Partition.scala:846)
	at kafka.cluster.Partition.makeLeader(Partition.scala:802)
	at kafka.server.streamaspect.ElasticReplicaManager.$anonfun$applyLocalLeadersDelta$3(ElasticReplicaManager.scala:1165)
	at kafka.server.streamaspect.ElasticReplicaManager$$Lambda$2275/0x0000000801899b60.accept(Unknown Source)
	at kafka.server.streamaspect.ElasticReplicaManager.getOrCreatePartitionV2(ElasticReplicaManager.scala:938)
	at kafka.server.streamaspect.ElasticReplicaManager.$anonfun$applyLocalLeadersDelta$2(ElasticReplicaManager.scala:1162)
	at kafka.server.streamaspect.ElasticReplicaManager.$anonfun$applyLocalLeadersDelta$2$adapted(ElasticReplicaManager.scala:1161)
	at kafka.server.streamaspect.ElasticReplicaManager$$Lambda$2247/0x000000080189f620.apply(Unknown Source)
	at kafka.utils.Implicits$MapExtensionMethods$.$anonfun$forKeyValue$1(Implicits.scala:62)
	at kafka.server.streamaspect.ElasticReplicaManager$$Lambda$2264/0x00000008018a1c70.apply(Unknown Source)
	at scala.collection.mutable.HashMap$Node.foreachEntry(HashMap.scala:648)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:514)
	at kafka.server.streamaspect.ElasticReplicaManager.applyLocalLeadersDelta(ElasticReplicaManager.scala:1161)
	at kafka.server.streamaspect.ElasticReplicaManager.$anonfun$asyncApplyDelta$12(ElasticReplicaManager.scala:1078)
	at kafka.server.streamaspect.ElasticReplicaManager$$Lambda$2234/0x000000080189c4f8.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.7/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.7/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.7/Thread.java:833)

**Comment by lifepuzzlefun** [comment]
the heap dump i cant provide and after the check the read for LocalNodeIndex may not contain the latest information and not refreshed cause the read operation forever loop

**Comment by lifepuzzlefun** [comment]
<img width="1288" alt="image" src="https://github.com/user-attachments/assets/53e889c8-14ba-411c-920d-01255a71f22c">

**Comment by lifepuzzlefun** [comment]
@superhx please take a look.

**Comment by superhx** [comment]
cc @SCNieh
