### ISSUE TITLE
[BUG] AsyncObjectLRUCache ConcurrentModificationException

### ISSUE THREAD

**Issue by lifepuzzlefun** [AutoMQ/automq#1774]
### Version & Environment

master

### What went wrong?

```

[2024-08-12 19:34:26,680] ERROR error when loadStreamSetObjectInfo (org.apache.kafka.image.S3StreamsMetadataImage)
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:788)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:786)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:515)
	at java.base/java.util.stream.IntPipeline.sum(IntPipeline.java:473)
	at com.automq.stream.s3.cache.AsyncObjectLRUCache.totalSize(AsyncObjectLRUCache.java:63)
	at com.automq.stream.s3.cache.AsyncObjectLRUCache.evict(AsyncObjectLRUCache.java:37)
	at com.automq.stream.s3.cache.AsyncObjectLRUCache.put(AsyncObjectLRUCache.java:31)
	at com.automq.stream.s3.cache.blockcache.DefaultObjectReaderFactory.get(DefaultObjectReaderFactory.java:35)
	at kafka.log.stream.s3.metadata.StreamMetadataManager$DefaultRangeGetter.find(StreamMetadataManager.java:311)
	at org.apache.kafka.image.S3StreamsMetadataImage.loadStreamSetObjectInfo(S3StreamsMetadataImage.java:473)
	at org.apache.kafka.image.S3StreamsMetadataImage.lambda$fillObjects$5(S3StreamsMetadataImage.java:269)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
	at org.apache.kafka.image.S3StreamsMetadataImage.fillObjects(S3StreamsMetadataImage.java:259)
	at org.apache.kafka.image.S3StreamsMetadataImage.getObjects0(S3StreamsMetadataImage.java:192)
	at org.apache.kafka.image.S3StreamsMetadataImage.getObjects(S3StreamsMetadataImage.java:158)
	at kafka.log.stream.s3.metadata.StreamMetadataManager.fetch0(StreamMetadataManager.java:125)
	at kafka.log.stream.s3.metadata.StreamMetadataManager.lambda$fetch$1(StreamMetadataManager.java:115)
	at com.automq.stream.utils.FutureUtil.exec(FutureUtil.java:77)
	at kafka.log.stream.s3.metadata.StreamMetadataManager.fetch(StreamMetadataManager.java:115)
	at kafka.log.stream.s3.objects.ControllerObjectManager.getObjects(ControllerObjectManager.java:241)
	at com.automq.stream.s3.cache.blockcache.StreamReader.loadMoreBlocksWithoutData0(StreamReader.java:392)
```

### How to reproduce the issue?

1. have no idea

### Additional information
maybe jdk bug or the lru cache load and evict together.

**Comment by superhx** [comment]
Add a new `#thenAccept` to a CompletableFuture may execute the previous `#thenAccept` which append to that CompletableFuture

In this case: In `AsyncObjectLRUCache#totalSize` loop -> call `ObjectReader#size` -> execute `AsyncObjectLRUCache#put#evict` change the map -> cause ConcurrentModificationException

https://github.com/AutoMQ/automq/blob/ea3b294d000678c758deef1c12e3132bc4f9a8aa/s3stream/src/main/java/com/automq/stream/s3/cache/AsyncObjectLRUCache.java#L53-L64

https://github.com/AutoMQ/automq/blob/ea3b294d000678c758deef1c12e3132bc4f9a8aa/s3stream/src/main/java/com/automq/stream/s3/cache/AsyncObjectLRUCache.java#L30-L34

![image](https://github.com/user-attachments/assets/a4d84030-8a47-43e9-8f4b-1c2d29c5d811)

**Comment by lifepuzzlefun** [comment]
```java
@Test
    public void testConcurrentGetPut() throws InterruptedException {
        ObjectReaderLRUCache cache = new ObjectReaderLRUCache(1000);
        List<CompletableFuture<Integer>> cfs = new ArrayList<>();
        Random r = new Random();

        ExecutorService es = Executors.newFixedThreadPool(10);
        for (int j = 0; j < 10; j++) {
            es.submit(() -> {
                for (int i = 0; i < 3; i++) {
                    ObjectReader reader = Mockito.mock(ObjectReader.class);
                    CompletableFuture<Integer> cf = CompletableFuture.supplyAsync(() -> r.nextInt(1000),
                        CompletableFuture.delayedExecutor(r.nextInt(1000), TimeUnit.MICROSECONDS));
                    cfs.add(cf);
                    Mockito.doAnswer(invocation -> cf).when(reader).size();
                    cache.put((long) i, reader);
                }
            });
        }

        CompletableFuture.allOf(cfs.toArray(new CompletableFuture[0])).join();
        Thread.sleep(10000000);
        Assertions.assertEquals(50, cache.size());
    }
```

```java
package com.automq.stream.s3.cache;

import java.util.Optional;
import java.util.Queue;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.atomic.AtomicInteger;

public class AsyncObjectLRUCache<K, V extends AsyncMeasurable> extends LRUCache<K, V> {
    private final int maxSize;

    public AsyncObjectLRUCache(int maxSize) {
        super();
        if (maxSize <= 0) {
            throw new IllegalArgumentException("maxSize must be positive");
        }
        this.maxSize = maxSize;
    }

    @Override
    public synchronized void put(K key, V value) {
        evict();
        super.put(key, value);
        value.size().thenAccept(v -> evict());
    }

    private synchronized void evict() {
        AtomicInteger totalSize = new AtomicInteger(totalSize());
        while (totalSize.get() > maxSize) {
            Optional.ofNullable(pop()).ifPresent(entry -> {
                try {
                    CompletableFuture<Integer> cf = entry.getValue().size();
                    if (cf.isDone()) {
                        totalSize.addAndGet(-cf.get());
                    }
                    entry.getValue().close();
                } catch (Throwable t) {
                    // ignore
                    q.add(t);
                    t.printStackTrace();
                    Runtime.getRuntime().halt(1);
//                    return 0;
                }
            });
        }
    }

    static Queue<Throwable> q = new ConcurrentLinkedQueue<>();
    public synchronized int totalSize() {
        return cacheEntrySet.stream().mapToInt(entry -> {
//            if (!entry.getValue().size().isDone()) {
//                return 0;
//            }
            try {
                int number = entry.getValue().size().get();
                if (ThreadLocalRandom.current().nextInt(10) > 5) {
                    evict();
                }
                return number;
            } catch (Exception e) {
                q.add(e);
                e.printStackTrace();
                Runtime.getRuntime().halt(1);
                return 0;
            }
        }).sum();
    }
}
```
