### ISSUE TITLE
[BUG] The attribute unset error

### ISSUE THREAD

**Issue by superhx** [AutoMQ/automq#1960]
```
024-08-28 22:28:16.811 +0800 ERROR [com.automq.stream.s3.compact.CompactionManager]  [CompactionManager id=2] Commit force split request failed, ex: 
java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException: The attribute is set to -1
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:747)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182)
	at com.automq.stream.s3.compact.CompactionManager.forceSplitObjects(CompactionManager.java:333)
	at com.automq.stream.s3.compact.CompactionManager.compact(CompactionManager.java:301)
	at com.automq.stream.s3.compact.CompactionManager.lambda$compact$6(CompactionManager.java:236)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.UnsupportedOperationException: The attribute is set to -1
	at kafka.log.stream.s3.objects.ControllerObjectManager.commitStreamSetObject0(ControllerObjectManager.java:147)
	at kafka.log.stream.s3.objects.ControllerObjectManager.commitStreamSetObject(ControllerObjectManager.java:117)
	at com.automq.stream.s3.compact.CompactionManager.forceSplitObjects(CompactionManager.java:332)
	... 8 more
```

**Comment by Chillax-0v0** [comment]
Closed by #1961
