### ISSUE TITLE
[BUG] Fetch NPE in 3.7.0

### ISSUE THREAD

**Issue by superhx** [AutoMQ/automq#996]
```
76127, logStartOffset=-1, maxBytes=131072, currentLeaderEpoch=Optional[0], lastFetchedEpoch=Optional.empty)))  (kafka.server.streamaspect.ElasticReplicaManager)
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "cause" is null
	at org.apache.kafka.common.protocol.Errors.forException(Errors.java:529)
	at kafka.server.LogReadResult.error(ReplicaManager.scala:129)
	at kafka.server.LogReadResult.toFetchPartitionData(ReplicaManager.scala:133)
	at kafka.server.streamaspect.ElasticReplicaManager.$anonfun$fetchMessages$1(ElasticReplicaManager.scala:360)
	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:100)
	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:87)
	at scala.collection.mutable.ArrayBuffer.map(ArrayBuffer.scala:43)
	at kafka.server.streamaspect.ElasticReplicaManager.kafka$server$streamaspect$ElasticReplicaManager$$responseEmpty$1(ElasticReplicaManager.scala:359)
	at kafka.server.streamaspect.ElasticReplicaManager$$anon$2$$anon$3.run(ElasticReplicaManager.scala:392)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by superhx** [comment]
![image](https://github.com/AutoMQ/automq/assets/5719209/3c239a98-c7a2-4bda-af56-445591d8fc78)
![image](https://github.com/AutoMQ/automq/assets/5719209/4bb54e5b-0913-4f8d-a115-d87505e4aeff)
![image](https://github.com/AutoMQ/automq/assets/5719209/339336c4-61dd-4933-b2a2-9fd2f7937154)
